Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6043303109991704378">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6043303109991704378">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20150829080925

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6045839812915918486">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6045839812915918486">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20150905080928

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6053449925531554680">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6053449925531554680">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20150926080932

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6061060121359631968">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6061060121359631968">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20151017080946

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6063596836748100636">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6063596836748100636">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20151024080916

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6068670273396154545">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6068670273396154545">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20151107080922

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6071206983935800859">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6071206983935800859">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20151114080924

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6073743698054901325">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6073743698054901325">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20151121080923

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6076280415214024084">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6076280415214024084">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20151128080924

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6081353844427569835">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6081353844427569835">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20151212080928

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6086427270457524455">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6086427270457524455">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20151226080931

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6091500706542544690">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6091500706542544690">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160109080931

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6094037424318818354">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6094037424318818354">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160116080939

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6096574136917024969">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6096574136917024969">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160123080935

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6099110852533338977">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6099110852533338977">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160130080943

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6104184275756152887">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6104184275756152887">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160213080945

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6106720992528996208">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6106720992528996208">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160220080958

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6111794427404398791">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6111794427404398791">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160305080956

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6114331140928084537">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6114331140928084537">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160312080949

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6116867859090293753">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6116867859090293753">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160319081010

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6119404573367151563">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6119404573367151563">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160326081009

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6124477999290826085">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6124477999290826085">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160409080954

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6127014719023655010">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6127014719023655010">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160416081010

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6129551433924676337">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6129551433924676337">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160423081008

---

app.rb
test/app_test.rb
views/index.slim

```json
[{"series_name":"unmarked","title":"ふたりはプリキュア","started_date":"2004-02-01","ended_date":"2005-01-30","girls":["cure_black","cure_white"]},{"series_name":"max_heart","title":"ふたりはプリキュア Max Heart","started_date":"2005-02-06","ended_date":"2006-01-29","girls":["cure_black","cure_white","shiny_luminous"]},{"series_name":"splash_star","title":"ふたりはプリキュア Splash☆Star","started_date":"2006-02-05","ended_date":"2007-01-28","girls":["cure_bloom","cure_egret"]},{"series_name":"yes","title":"Yes！ プリキュア5","started_date":"2007-02-04","ended_date":"2008-01-27","girls":["cure_dream","cure_rouge","cure_lemonade","cure_mint","cure_aqua"]},{"series_name":"yes_gogo","title":"Yes！ プリキュア5 Go Go！","started_date":"2008-02-03","ended_date":"2009-01-25","girls":["cure_dream","cure_rouge","cure_lemonade","cu …
```

Support pretty json format

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6134624856990545042">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6134624856990545042">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160507081006

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6137161572680419966">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6137161572680419966">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160514081008

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6139698294265420981">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6139698294265420981">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160521081015

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6144771721059446538">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6144771721059446538">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160604081013

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6147308433102349001">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6147308433102349001">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160611081009

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6149845151802098516">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6149845151802098516">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160618081021

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6162528721712954232">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6162528721712954232">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160723080912

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6167602153022399179">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6167602153022399179">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160806080917

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6170138868908538775">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6170138868908538775">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160813080922

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6172675583667660725">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6172675583667660725">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160820080922

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6180285727584143455">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6180285727584143455">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160910080922

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6182822444363379202">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6182822444363379202">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160917080923

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6185359159368742989">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6185359159368742989">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160924080935

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6187895872509169627">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6187895872509169627">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20161001080925

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6190432593247316622">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6190432593247316622">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20161008080936

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6200579451777182888">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6200579451777182888">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20161105080935

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6203116169320393788">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6203116169320393788">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20161112080945

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6205652884269366046">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6205652884269366046">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20161119080948

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6208189593827744179">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6208189593827744179">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20161126080940

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6213263028916835406">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6213263028916835406">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20161210080945

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6215799743833460974">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6215799743833460974">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20161217080954

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6218336463890534898">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6218336463890534898">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20161224081002

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6220873168402701436">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6220873168402701436">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20161231080955

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6228483313697157371">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6228483313697157371">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20170121080912

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6231020031273976324">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6231020031273976324">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20170128080911

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6236093461457801415">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6236093461457801415">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20170211080912

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6238630182016906427">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6238630182016906427">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20170218080913

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6243703604346393296">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6243703604346393296">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20170304080911

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6246240324642341893">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6246240324642341893">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20170311080913

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6248777035078809377">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6248777035078809377">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20170318080912

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6251313754081094653">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6251313754081094653">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20170325080912

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6253850466014357493">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6253850466014357493">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20170401080911

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6263997324354346658">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6263997324354346658">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20170429080911

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6266534042426515345">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6266534042426515345">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20170506080911

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6269070756793237503">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6269070756793237503">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20170513080912

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6271607471306803744">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6271607471306803744">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20170520080910

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6274144184537316901">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6274144184537316901">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20170527080910

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6279217619057598935">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6279217619057598935">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20170610080911

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6281754332895017568">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6281754332895017568">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20170617080910

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6284291052418238888">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6284291052418238888">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20170624080912

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6286827761306383302">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6286827761306383302">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20170701080912

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6289364475118578085">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6289364475118578085">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20170708080910

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6291901190521058085">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6291901190521058085">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20170715080910

---

app.rb

```sh
$ curl -s --include http://localhost:3000/girls/cure_parfait.json?format=pretty | grep "Content-Type:"
Content-Type: application/json
```
```sh
$ curl -s --include http://localhost:3000/girls/cure_parfait.json?format=pretty | grep "Content-Type:"
Content-Type: application/json; charset=UTF-8
```

Add UTF-8 to response header

---

Gemfile
Gemfile.lock
app.rb
views/index.slim

Add latest birthdays

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6294437913060469843">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6294437913060469843">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20170722080913

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6296974619894256804">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6296974619894256804">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20170729080910

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6299511343081565434">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6299511343081565434">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20170805080912

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6304584765357883996">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6304584765357883996">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20170819080911

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6318071973229291825">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6318071973229291825">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20170925132231

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6323145402592659150">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6323145402592659150">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20171009132232

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6328218832165066186">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6328218832165066186">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20171023132230

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6330755546970826029">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6330755546970826029">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20171030132230

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6333292263237174944">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6333292263237174944">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20171106132231

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6335828980237523288">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6335828980237523288">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20171113132231

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6338365692292712261">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6338365692292712261">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20171120132231

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6340902407418607746">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6340902407418607746">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20171127132232

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6345975836484391706">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6345975836484391706">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20171211132230

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6348512558544119386">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6348512558544119386">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20171218132233

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6356122698723352304">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6356122698723352304">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20180108132235

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6361196127669319828">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6361196127669319828">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20180122132231

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6366269556237469596">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6366269556237469596">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20180205132231

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6368806271350323204">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6368806271350323204">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20180212132230

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6376416416872572609">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6376416416872572609">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20180305132231

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6389099996000624184">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6389099996000624184">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20180409132232

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6394173426836618444">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6394173426836618444">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20180423132232

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6395406356490165390">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6395406356490165390">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20180426230145

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6403015246354633803">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6403015246354633803">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20180517225649

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6408088671008816861">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6408088671008816861">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20180531225644

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6410625389639783432">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6410625389639783432">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20180607225645

---

views/index.slim

Embed google calendar

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6434050797351439543">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6434050797351439543">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20180811142058

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6439124226295850378">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6439124226295850378">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20180825142058

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6441660942999321963">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6441660942999321963">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20180901142058

---

.rubocop.yml

Reverts sue445/rubicure_api#206

Revert "Upgrade TargetRubyVersion"
